spring.application.name=studyflow

spring.data.mongodb.uri=mongodb://localhost:27017/study_flow
spring.data.mongodb.auto-index-creation=true

jwt.secret=A0ZCaaiKUL70ktFcB3gJEZ5wFGUQdQwcnXB9JR3Ebbl
jwt.expiration=12000000