spring.application.name=studyflow

spring.mongodb.uri=mongodb://mongodb:27017/study_flow
spring.mongodb.representation.uuid=standard
spring.data.mongodb.auto-index-creation=true

jwt.secret=A0ZCaaiKUL70ktFcB3gJEZ5wFGUQdQwcnXB9JR3Ebbl
jwt.expiration=12000000